### ISSUE TITLE
Still active / used?

### ISSUE THREAD

**Issue by kinsi55** [msurdi/tcache#2]
Hey,

seeing as the last change was in 2015 I am wondering if this module is still something that you actively use / work on.

If not I was wondering if maybe it would be possible to get the name for a module of mine.

Thanks in advance!

**Comment by msurdi** [comment]
Hi there! I built this long time ago for solving a CI build performance problem. I'm not sure if nowadays those CI builds are still running because this was many years ago, so I can't confirm it is being actively used. It is still maintained in the sense that if there is any issue, I would do my best to fix it.

Anyways, in general, I'm of the opinion that it is a really bad idea to reuse names in any packaging system, this could lead to confusion and security issues. And some other minor inconveniences like you not being able to use the version numbers I already used here.

So, I'm very sorry, but mostly due to the security concern I wouldn't be willing to release the name, even if that could be technically done in npmjs.com.

**Comment by kinsi55** [comment]
Alright np, thank you anways
